# Generated by Django 5.0.2 on 2024-02-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Uno', 'Uno'), ('Baldi', 'Baldi'), ('Addidas', 'Addidas'), ('Puma', 'Puma'), ('Nike', 'Nike')], max_length=10)),
                ('size', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.PositiveSmallIntegerField()),
                ('model', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoe',
            },
        ),
    ]
