# Generated by Django 5.0.2 on 2024-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
