# Generated by Django 5.0.2 on 2024-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shoes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
